export const ALL_PRODUCT_REQUEST="ALL_PRODUCT_REQUEST";
export const ALL_PRODUCT_SUCCESS="ALL_PRODUCT_SUCCESS";
export const ALL_PRODUCT_FAIL="ALL_PRODUCT_FAIL";

export const NEW_PRODUCT_REQUEST="NEW_PRODUCT_REQUEST";
export const NEW_PRODUCT_SUCCESS="NEW_PRODUCT_SUCCESS";
export const NEW_PRODUCT_FAIL="NEW_PRODUCT_FAIL";
export const NEW_PRODUCT_RESET="NEW_PRODUCT_RESET";

export const DELETE_PRODUCT_REQUEST="DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_SUCCESS="DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAIL="DELETE_PRODUCT_FAIL";
export const DELETE_PRODUCT_RESET="DELETE_PRODUCT_RESET";

export const UPDATE_PRODUCT_REQUEST="UPDATE_PRODUCT_REQUEST";
export const UPDATE_PRODUCT_SUCCESS="UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_FAIL="UPDATE_PRODUCT_FAIL";
export const UPDATE_PRODUCT_RESET="UPDATE_PRODUCT_RESET";


export const ALL_DETAIL_REQUEST="ALL_DETAIL_REQUEST";
export const ALL_DETAIL_SUCCESS="ALL_DETAIL_SUCCESS";
export const ALL_DETAIL_FAIL="ALL_DETAIL_FAIL";

export const ADMIN_PRODUCT_REQUEST="ADMIN_PRODUCT_REQUEST";
export const ADMIN_PRODUCT_SUCCESS="ADMIN_PRODUCT_SUCCESS";
export const ADMIN_PRODUCT_FAIL="ADMIN_PRODUCT_FAIL";

export const GET_REVIEW_REQUEST="GET_REVIEW_REQUEST";
export const GET_REVIEW_SUCCESS="GET_REVIEW_SUCCESS";
export const GET_REVIEW_FAIL="GET_REVIEW_FAIL";

export const DELETE_REVIEW_REQUEST="DELETE_REVIEW_REQUEST";
export const DELETE_REVIEW_SUCCESS="DELETE_REVIEW_SUCCESS";
export const DELETE_REVIEW_FAIL="DELETE_REVIEW_FAIL";
export const DELETE_REVIEW_RESET="DELETE_REVIEW_RESET";

export const PRODUCT_REVIEW_REQUEST="PRODUCT_REVIEW_REQUEST";
export const PRODUCT_REVIEW_SUCCESS="PRODUCT_REVIEW_SUCCESS";
export const PRODUCT_REVIEW_FAIL="PRODUCT_REVIEW_FAIL";
export const PRODUCT_REVIEW_RESET="PRODUCT_REVIEW_RESET";

export const CLEAR_ERRORS="CLEAR_ERRORS";