export const Login_REQUEST="Login_REQUEST";
export const Login_SUCCESS="Login_SUCCESS";
export const Login_FAIL="Login_FAIL";

export const REGISTER_REQUEST="REGISTER_REQUEST";
export const REGISTER_SUCCESS="REGISTER_SUCCESS";
export const REGISTER_FAIL="REGISTER_FAIL";


export const LOAD_REQUEST="LOAD_REQUEST";
export const LOAD_SUCCESS="LOAD_SUCCESS";
export const LOAD_FAIL="LOAD_FAIL";

export const PROFILE_REQUEST="PROFILE_REQUEST";
export const PROFILE_SUCCESS="PROFILE_SUCCESS";
export const PROFILE_FAIL="PROFILE_FAIL";
export const PROFILE_RESET="PROFILE_RESET";

export const PASSWORD_REQUEST="PASSWORD_REQUEST";
export const PASSWORD_SUCCESS="PASSWORD_SUCCESS";
export const PASSWORD_FAIL="PASSWORD_FAIL";
export const PASSWORD_RESET="PASSWORD_RESET";


export const FORGOT_PASSWORD_REQUEST="FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS="FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAIL="FORGOT_PASSWORD_FAIL";

export const RESET_PASSWORD_REQUEST="RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS="RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL="RESET_PASSWORD_FAIL";

export const USER_DETAIL_REQUEST="USER_DETAIL_REQUEST";
export const USER_DETAIL_SUCCESS="USER_DETAIL_SUCCESS";
export const USER_DETAIL_FAIL="USER_DETAIL_FAIL";

export const USER_UPDATE_REQUEST="USER_UPDATE_REQUEST";
export const USER_UPDATE_SUCCESS="USER_UPDATE_SUCCESS";
export const USER_UPDATE_FAIL="USER_UPDATE_FAIL";
export const USER_UPDATE_RESET="USER_UPDATE_RESET";

export const USER_DELETE_REQUEST="USER_DELETE_REQUEST";
export const USER_DELETE_SUCCESS="USER_DELETE_SUCCESS";
export const USER_DELETE_FAIL="USER_DELETE_FAIL";
export const USER_DELETE_RESET="USER_DELETE_RESET";

export const ALL_USER_REQUEST="ALL_USER_REQUEST";
export const ALL_USER_SUCCESS="ALL_USER_SUCCESS";
export const ALL_USER_FAIL="ALL_USER_FAIL";


export const LOGOUT_SUCCESS="LOGOUT_SUCCESS";
export const LOGOUT_FAIL="LOGOUT_FAIL";